### ISSUE TITLE
Made the code cell blocks wider

### ISSUE THREAD

**Issue by melvinev** [fredericosantos/jupyterlab-fsx-monokai-theme#5]
Hi thank you for the theme!  I love the style however my cell blocks are not nearly as wide as normal, if I max my screen they are centered and not wide. 

Is there a way to widen them?  Or I could fork the project and then make changes?

**Comment by melvinev** [comment]
Maybe this is causing it?  You have both of these in the CSS.  Maybe if you just remove the max-width: 1000px then the max-width: 95% would work? 

/* Max-widht for main content/cell blocks */ 
.jp-Notebook .jp-Cell { max-width: 1000px; margin: auto; }

.jp-Notebook .jp-Cell { max-width: 95%; margin: auto; }

**Comment by melvinev** [comment]
Thank you @fredericosantos I saw you made a commit to master and I redownloaded and it works GREAT now.  Honestly the nicest theme out there... I've been hunting for this.  THANK YOU!

**Comment by fredericosantos** [comment]
Hi @melvinev ! Thank you for appreciating my theme! I'm very new to CSS and HTML5 and programming as a whole, so thank you for your patience! My plan is to constantly improve upon this theme over the coming months as I use JupyterLab more and more! Please make as many requests as you can!

I couldn't answer you because github was blocked on my wifi network, but I updated it right away :)
